### PR TITLE
Added per-player volume control when right-clicking speaker icons.

### PR DESCRIPTION
**Pull request by Physics-Dude**
Added ShowMicVolumeSlider() and respective call when player's speaker button is right-clicked in the scoreboard. Same thing that vanilla Garry's Mod now does. 

unknown

### CODE REVIEW

**Comment by Physics-Dude** [comment]
Updated the theme to match.

unknown

**Comment by juliocoliveira** [comment]
I tested and the right click on the volume icon is doing nothing. A least on my own row can't test on others.

**Comment by juliocoliveira** [comment]
I seams that it does not work on myself intentionally. There is a "ply ~= LocalPlayer()"

**Comment by juliocoliveira** [comment]
I temporary removed the condition to test, and the menu works, now if the volume changer works i cannot test it. But i'll commit the changes to workshop as well.

**Pull request merged**
